### ISSUE TITLE
scan match

### ISSUE THREAD

**Issue by xbcdbc** [libing64/slam2d#1]
scan-to-scan just iterate closest point one time?

**Comment by libing64** [comment]
The initial value is the result of previous scan-to-scan-match, and point-to-line constaint reduces the requirement for accurate correspondence, so one time iteration is enough.

**Comment by xbcdbc** [comment]
but in the case of fast rotation, the result may degrade?

**Comment by libing64** [comment]
@xbcdbc If the angular accleration is not too large, I think it's OK.
